name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Lint (flake8)
        run: |
          flake8 src app.py scripts --ignore=E501,W503
      - name: Import smoke tests
        run: |
          python - << 'PY'
          import importlib
          import sys
          for mod in ['app','src.pipeline.predict_pipeline']:
              importlib.import_module(mod)
          print('Imports OK')
          PY
      - name: Run unit tests
        run: pytest -q
